### ISSUE TITLE
Legend Issues

### ISSUE THREAD

**Issue by Ronin11** [d3-node/d3-node#28]
When trying to add a simple legend to my graph it throws the following error:
TypeError: Cannot read property 'apply' of undefined
From the following location: d3-selection/build/d3-selection.js:500:11
```
svg.append('g')
        .attr('class','legend')
        .attr('transform','translate(50,30)')
	.style('font-size','12px')
	.call(d3.legend)
```

**Comment by bradoyler** [comment]
@Ronin11 how was the `svg` object created?

**Comment by Ronin11** [comment]
```
	const svg = d3n.createSVG(_width, _height)
		.append('g')
		.attr('transform', `translate(${margin.left}, ${margin.top})`);
```

**Comment by geekplux** [comment]
@Ronin11 your `svg` creation seems no error, and where is d3.legend code? I should reproduce this bug.

**Comment by Ronin11** [comment]
In the first comment

**Comment by geekplux** [comment]
@Ronin11 sorry, I mean the details implementation of d3.legend . because I don't know what object or function it called.

**Comment by Ronin11** [comment]
```
var line = function(data){
	var selector = '#chart';
	var container = `
	<div id="container">
		<h2>Line Chart</h2>
		<div id="chart"></div>
	</div>
	`;
	var _width = 960;
	var _height = 500;
	var margin = { top: 20, right: 20, bottom: 60, left: 75 };
	var lineWidth = 1.5;
	var tickSize = 5;
	var tickPadding = 5;

const d3n = new D3Node({
	selector: selector,
	container: container,
	});

	const d3 = d3n.d3;

	const width = _width - margin.left - margin.right;
	const height = _height - margin.top - margin.bottom;

	const svg = d3n.createSVG(_width, _height)
		.append('g')
		.attr('transform', `translate(${margin.left}, ${margin.top})`);

	
	// parse the date / time
	var parseTime = d3.timeParse("%Y");

	// set the ranges
	var x = d3.scaleTime().range([0, width]);
	var y = d3.scaleLinear().range([height, 0]);

	// define the 1st line
	var valueline = d3.line()
		.x(function(d) { return x(d.fiscalYear); })
		.y(function(d) { return y(d.specimenTotal); });

	// valueline.curve(d3.curveBasis);//Smooths data transition


	// append the svg obgect to the body of the page
	// appends a 'group' element to 'svg'
	// moves the 'group' element to the top left margin
	const g = svg.append('g')
			.attr('width', width + margin.left + margin.right)
			.attr('height', height + margin.top + margin.bottom)
		.append('g')
			.attr('transform',
				'translate(' + margin.left + ',' + margin.top + ')');

	// format the data
	data.forEach(function(d) {
		d.fiscalYear = parseTime(d.fiscalYear);
		if(d.specimenTotal)
			d.specimenTotal = +d.specimenTotal;
		else
			d.specimenTotal = 0;
	});

	// Scale the range of the data
	x.domain(d3.extent(data, function(d) { return d.fiscalYear; }));
	y.domain([0, d3.max(data, function(d) {
		return Math.max(d.specimenTotal); })]);

	// Add the valueline path.
	svg.append('path')
		.data([data])
		.attr('fill', 'none')
		.attr('class', 'line')
		.attr('stroke-width', lineWidth)
		.style('stroke', 'steelblue')
		.attr('d', valueline);

	// Add the X Axis
	svg.append('g')
		.attr('transform', 'translate(0,' + height + ')')
		.call(d3.axisBottom(x));

	// Add the Y Axis
	svg.append('g')
		.call(d3.axisLeft(y));

	//Add legend
	// svg.append('g')
	// 	.attr('class','legend')
	// 	.attr('transform','translate(50,30)')
	// 	.style('font-size','12px')
	// 	.call(d3.legend)

	return d3n;
}
```

**Comment by Ronin11** [comment]
I've been finding examples like these:
http://bl.ocks.org/ZJONSSON/3918369

d3.legend is just a member function of d3. As far as I can tell, it just gets all of the datasets attached to the graph and throws them on the screen with some prettiness.

Here's the entire function:
```
var line = function(data){
	var selector = '#chart';
	var container = `
	<div id="container">
		<h2>Line Chart</h2>
		<div id="chart"></div>
	</div>
	`;
	var _width = 960;
	var _height = 500;
	var margin = { top: 20, right: 20, bottom: 60, left: 75 };
	var lineWidth = 1.5;
	var tickSize = 5;
	var tickPadding = 5;

const d3n = new D3Node({
	selector: selector,
	container: container,
	});

	const d3 = d3n.d3;

	const width = _width - margin.left - margin.right;
	const height = _height - margin.top - margin.bottom;

	const svg = d3n.createSVG(_width, _height)
		.append('g')
		.attr('transform', `translate(${margin.left}, ${margin.top})`);

	
	// parse the date / time
	var parseTime = d3.timeParse("%Y");

	// set the ranges
	var x = d3.scaleTime().range([0, width]);
	var y = d3.scaleLinear().range([height, 0]);

	// define the 1st line
	var valueline = d3.line()
		.x(function(d) { return x(d.fiscalYear); })
		.y(function(d) { return y(d.specimenTotal); });

	// valueline.curve(d3.curveBasis);//Smooths data transition


	// append the svg obgect to the body of the page
	// appends a 'group' element to 'svg'
	// moves the 'group' element to the top left margin
	const g = svg.append('g')
			.attr('width', width + margin.left + margin.right)
			.attr('height', height + margin.top + margin.bottom)
		.append('g')
			.attr('transform',
				'translate(' + margin.left + ',' + margin.top + ')');

	// format the data
	data.forEach(function(d) {
		d.fiscalYear = parseTime(d.fiscalYear);
		if(d.specimenTotal)
			d.specimenTotal = +d.specimenTotal;
		else
			d.specimenTotal = 0;
	});

	// Scale the range of the data
	x.domain(d3.extent(data, function(d) { return d.fiscalYear; }));
	y.domain([0, d3.max(data, function(d) {
		return Math.max(d.specimenTotal); })]);

	// Add the valueline path.
	svg.append('path')
		.data([data])
		.attr('fill', 'none')
		.attr('class', 'line')
		.attr('stroke-width', lineWidth)
		.style('stroke', 'steelblue')
		.attr('d', valueline);

	// Add the X Axis
	svg.append('g')
		.attr('transform', 'translate(0,' + height + ')')
		.call(d3.axisBottom(x));

	// Add the Y Axis
	svg.append('g')
		.call(d3.axisLeft(y));

	//Add legend
	svg.append('g')
	 	.attr('class','legend')
	 	.attr('transform','translate(50,30)')
	 	.style('font-size','12px')
	 	.call(d3.legend)

	return d3n;
}
```

**Comment by MrVine** [comment]
I have the same problem. I use the same code to create `legend` (from [here](https://gist.github.com/ZJONSSON/3918369)): 

```
var legend = svg.append("g")
  .attr("class","legend")
  .attr("transform","translate(50,30)")
  .style("font-size","12px")
  .call(d3.legend)
```

And I use following code to specify [data-legend]:

```
svg.append("g")
    .append("path")
    .attr("d", path)
    .attr("fill", function (d) { return color(d.data.label); })
    .attr("data-legend", function (d) { return d.label })
    .attr("stroke", function (d) { return color(d.data.label); })
```

As response I get following error message:

```
Cannot read property 'apply' of undefined
TypeError: Cannot read property 'apply' of undefined
at Selection.selection_call [as call] (F:\Projects\ProjectName\node_modules\d3-selection\dist\d3-selection.js:338:12)
at module.exports (F:\Projects\ProjectName\my-node-modules\pie_chart.js:66:10)
```

where `pie_chart.js:66` line contains following code: .`call(d3.legend);`, and `d3-selection.js` contains following lines:

```
335:    function selection_call() {
336:        var callback = arguments[0];
337:        arguments[0] = this;
**338**:        callback.apply(null, arguments);
339:        return this;
340:    }
```

So, there is a bug inside d3-node?
How can I fix it?

**Comment by geekplux** [comment]
what would happen if you try to use:

```js
legend = svg.append("g")
  .attr("class","legend")
  .attr("transform","translate(50,30)")
  .style("font-size","12px")

d3.legend(legend)
```

**Comment by MrVine** [comment]
@geekplux , I didn't try, and I think it is unnecessary step, because `console.log(d3.legend)` returns `undefined`. Do I need some `require()` to use `d3.legend()` function?

**Comment by geekplux** [comment]
@MrVine yes, you should `import` or `require` every module before using it

**Comment by MrVine** [comment]
I have `const d3 = require('d3');`, but why `d3.legend` is undefined? How can I `require` it?

**Comment by geekplux** [comment]
@MrVine I saw the `d3.legend`'s source code. It assigns a function to d3 as its property, so `d3.legend` run in browser well. If you wanna use it in node environment, you'd better copy the source code of `d3.legend` into a .js file and import it as a function and not the d3 property, such as:

```js
import d3legend from './d3legend.js';
var legend = svg.append("g")
  .attr("class","legend")
  .call(d3legend);
```

**Comment by bradoyler** [comment]
@MrVine you need to require the `d3.legend.js` file from the example. It is not included in any d3 builds
