### ISSUE TITLE
Is this package still working for recent versions?

### ISSUE THREAD

**Issue by jgclark** [d3-node/d3-node#61]
I'm new at D3 and was very pleased to find this package to help me produce SVG or PNG charts on the server. But I can't get going with it, and I wonder if it still works?
Here's what I have loaded (on macOS 11.6 with node 17.0.1):
```
d3tests:
├── d3-node@2.2.3
├── d3@7.1.1
├── d3node-barchart@0.1.1
├── d3node-output@1.0.3
└── d3node-piechart@0.0.10
```
Here's my minimal case, cobbled together from your various docs:
```
const fs = require('fs');
const d3 = require('d3-node')().d3;
const output = require('d3node-output');
const d3nBar = require('d3node-barchart');
// const d3nPie = require('d3node-piechart');
const csvString=`key,value
Bob,33
Robin,12
...
Charles,13
Mary,29`
const csvData = d3.csvParse(csvString);

const selector = `#chart`
const container = `<div id="container"><h2>Bar Chart</h2><div id="chart"></div></div>`
const style = `.bar{fill: steelblue;}
.bar:hover{fill: brown;}
.axis{font: 10px sans-serif;}
.axis path,.axis line{fill: none;stroke: #000;shape-rendering: crispEdges;}
.x.axis path{display: none;}`

// create output files
// const pie = d3nPie(csvData, selector, container, style)
const bar = d3nBar(csvData, selector, container, style)
output('output', bar);
```
I (and a friend on a completely different modern system) get this error:
```
/Users/jonathan/Dropbox/NPSummaries/NP-other-tests/node_modules/d3node-barchart/index.js:55
  x.domain(data.map((d) => d.key));
                ^

TypeError: Cannot read properties of undefined (reading 'map')
    at bar (/Users/jonathan/Dropbox/NPSummaries/NP-other-tests/node_modules/d3node-barchart/index.js:55:17)
```
If I comment out the `barchart` lines and use `piechart` instead I get this error:
```
/Users/jonathan/Dropbox/NPSummaries/NP-other-tests/node_modules/d3node-piechart/node_modules/d3-shape/build/d3-shape.js:504
        n = data.length,
                 ^

TypeError: Cannot read properties of undefined (reading 'length')
    at pie (/Users/jonathan/Dropbox/NPSummaries/NP-other-tests/node_modules/d3node-piechart/node_modules/d3-shape/build/d3-shape.js:504:18)
```
Any advice, please?

**Comment by jgclark** [comment]
I asked on [SO overflow as well](https://stackoverflow.com/questions/69778492/best-way-to-use-recent-d3-versions-to-produce-pngs-from-node-js/69827159#69827159), and Mehdi found it was a documentation error. I will raise a PR.

**Comment by jgclark** [comment]
I have raised PRs on 2 child projects. Others will presumably need updating as well.

**Comment by bradoyler** [comment]
we also have an example in those repos. Thx for fixing the readme.
